// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'shared/model/image.entity.dart';
import 'shared/model/search.entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2663144698117126136),
    name: 'SearchQuery',
    lastPropertyId: const obx_int.IdUid(4, 1454935476442684565),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2553049354797290567),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4299684325954142233),
        name: 'text',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 5815231524596225675),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1454935476442684565),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5043420744528449525),
    name: 'ImageObjectBox',
    lastPropertyId: const obx_int.IdUid(4, 4696879542942844184),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 859285058173673911),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7130088022235307144),
        name: 'assetId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(6, 5572759801300789294),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4360099693225361642),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(7, 2419459409395599829),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4696879542942844184),
        name: 'indexedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5043420744528449525),
    lastIndexId: const obx_int.IdUid(7, 2419459409395599829),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [1561470879124125729, 4579256638745705832],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5503804796325456193,
      1936530908489758914,
      3027495112137255621,
      8406163916037868059,
      8236889083046583962,
      7364861189981264080,
      4902416859858591108,
      5122337035740735393,
      4925822784491038955,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SearchQuery: obx_int.EntityDefinition<SearchQuery>(
      model: _entities[0],
      toOneRelations: (SearchQuery object) => [],
      toManyRelations: (SearchQuery object) => {},
      getId: (SearchQuery object) => object.id,
      setId: (SearchQuery object, int id) {
        object.id = id;
      },
      objectToFB: (SearchQuery object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          isUtc: true,
        );
        final object = SearchQuery(
          id: idParam,
          text: textParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    ImageObjectBox: obx_int.EntityDefinition<ImageObjectBox>(
      model: _entities[1],
      toOneRelations: (ImageObjectBox object) => [],
      toManyRelations: (ImageObjectBox object) => {},
      getId: (ImageObjectBox object) => object.id,
      setId: (ImageObjectBox object, int id) {
        object.id = id;
      },
      objectToFB: (ImageObjectBox object, fb.Builder fbb) {
        final assetIdOffset = fbb.writeString(object.assetId);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, assetIdOffset);
        fbb.addOffset(2, embeddingOffset);
        fbb.addInt64(3, object.indexedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final assetIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final indexedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          isUtc: true,
        );
        final object = ImageObjectBox(
          idParam,
          assetIdParam,
          embeddingParam,
          indexedAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SearchQuery] entity fields to define ObjectBox queries.
class SearchQuery_ {
  /// See [SearchQuery.id].
  static final id = obx.QueryIntegerProperty<SearchQuery>(
    _entities[0].properties[0],
  );

  /// See [SearchQuery.text].
  static final text = obx.QueryStringProperty<SearchQuery>(
    _entities[0].properties[1],
  );

  /// See [SearchQuery.createdAt].
  static final createdAt = obx.QueryDateProperty<SearchQuery>(
    _entities[0].properties[2],
  );
}

/// [ImageObjectBox] entity fields to define ObjectBox queries.
class ImageObjectBox_ {
  /// See [ImageObjectBox.id].
  static final id = obx.QueryIntegerProperty<ImageObjectBox>(
    _entities[1].properties[0],
  );

  /// See [ImageObjectBox.assetId].
  static final assetId = obx.QueryStringProperty<ImageObjectBox>(
    _entities[1].properties[1],
  );

  /// See [ImageObjectBox.embedding].
  static final embedding = obx.QueryHnswProperty<ImageObjectBox>(
    _entities[1].properties[2],
  );

  /// See [ImageObjectBox.indexedAt].
  static final indexedAt = obx.QueryDateProperty<ImageObjectBox>(
    _entities[1].properties[3],
  );
}
