// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/feature/gallery/data/objectbox_trash_entry.dart';
import 'src/feature/indexing/data/objectbox_image_embedding.dart';
import 'src/feature/indexing/data/search_objectbox_model.dart';
import 'src/shared/domain/model/album.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 2663144698117126136),
    name: 'SearchQuery',
    lastPropertyId: const obx_int.IdUid(4, 1454935476442684565),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2553049354797290567),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4299684325954142233),
        name: 'text',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 5815231524596225675),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 1454935476442684565),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 3308344578776231510),
    name: 'ObjectBoxTrashEntry',
    lastPropertyId: const obx_int.IdUid(3, 8190675144603662551),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8882868979833481190),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 404277907193553463),
        name: 'assetId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(8, 6614934186557400277),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8190675144603662551),
        name: 'trashedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(9, 8273342539676853360),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(7, 5167160291219839134),
    name: 'ObjectBoxAlbum',
    lastPropertyId: const obx_int.IdUid(4, 4185198081818703660),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6834902613715951441),
        name: 'objectBoxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2523939935320921728),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2501778018105789813),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4185198081818703660),
        name: 'platformId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(10, 258238646482860556),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(9, 1721730835871466479),
    name: 'ObjectBoxAlbumTrashEntry',
    lastPropertyId: const obx_int.IdUid(3, 6554121543465052767),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5291209764634765604),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8052264120116243379),
        name: 'albumId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(13, 1109444958506980282),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6554121543465052767),
        name: 'trashedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(14, 5445266917403499267),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(10, 3585069197008563609),
    name: 'ObjectBoxImageEmbedding',
    lastPropertyId: const obx_int.IdUid(10, 8512386866158165320),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2939553243866213424),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5457531615471372287),
        name: 'assetId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(15, 6459110455456870627),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7481194980454731080),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7912331103047809102),
        name: 'mediaType',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5721591049721052584),
        name: 'duration',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3004988502034339002),
        name: 'embedding',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(16, 9060887394805760801),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 953338869357707116),
        name: 'indexedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8440508038984937772),
        name: 'mediaCreatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3032693642751473318),
        name: 'mediaModifiedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 8512386866158165320),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(10, 3585069197008563609),
    lastIndexId: const obx_int.IdUid(16, 9060887394805760801),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [
      1561470879124125729,
      4579256638745705832,
      6948439073829930918,
      2818964444761599636,
      5043420744528449525,
    ],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      5503804796325456193,
      1936530908489758914,
      3027495112137255621,
      8406163916037868059,
      8236889083046583962,
      7364861189981264080,
      4902416859858591108,
      5122337035740735393,
      4925822784491038955,
      2740278633346680692,
      8718488453534067771,
      131951363468051406,
      8360917123897941686,
      3182848755641666981,
      4348689481054691837,
      977867506931564729,
      859285058173673911,
      7130088022235307144,
      4360099693225361642,
      4696879542942844184,
      5523354732516403391,
      8584243545755849456,
      678764103683112610,
      2842926343622553362,
      3324893777632430676,
      6479119926179794594,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    SearchQuery: obx_int.EntityDefinition<SearchQuery>(
      model: _entities[0],
      toOneRelations: (SearchQuery object) => [],
      toManyRelations: (SearchQuery object) => {},
      getId: (SearchQuery object) => object.id,
      setId: (SearchQuery object, int id) {
        object.id = id;
      },
      objectToFB: (SearchQuery object, fb.Builder fbb) {
        final textOffset = fbb.writeString(object.text);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, textOffset);
        fbb.addInt64(3, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
          isUtc: true,
        );
        final object = SearchQuery(
          id: idParam,
          text: textParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
    ObjectBoxTrashEntry: obx_int.EntityDefinition<ObjectBoxTrashEntry>(
      model: _entities[1],
      toOneRelations: (ObjectBoxTrashEntry object) => [],
      toManyRelations: (ObjectBoxTrashEntry object) => {},
      getId: (ObjectBoxTrashEntry object) => object.id,
      setId: (ObjectBoxTrashEntry object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxTrashEntry object, fb.Builder fbb) {
        final assetIdOffset = fbb.writeString(object.assetId);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, assetIdOffset);
        fbb.addInt64(2, object.trashedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final assetIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final trashedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final object = ObjectBoxTrashEntry(
          assetId: assetIdParam,
          trashedAt: trashedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ObjectBoxAlbum: obx_int.EntityDefinition<ObjectBoxAlbum>(
      model: _entities[2],
      toOneRelations: (ObjectBoxAlbum object) => [],
      toManyRelations: (ObjectBoxAlbum object) => {},
      getId: (ObjectBoxAlbum object) => object.objectBoxId,
      setId: (ObjectBoxAlbum object, int id) {
        object.objectBoxId = id;
      },
      objectToFB: (ObjectBoxAlbum object, fb.Builder fbb) {
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final platformIdOffset = fbb.writeString(object.platformId);
        fbb.startTable(5);
        fbb.addInt64(0, object.objectBoxId);
        fbb.addOffset(1, titleOffset);
        fbb.addOffset(2, descriptionOffset);
        fbb.addOffset(3, platformIdOffset);
        fbb.finish(fbb.endTable());
        return object.objectBoxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final objectBoxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final platformIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final object = ObjectBoxAlbum(
          objectBoxId: objectBoxIdParam,
          title: titleParam,
          description: descriptionParam,
          platformId: platformIdParam,
        );

        return object;
      },
    ),
    ObjectBoxAlbumTrashEntry:
        obx_int.EntityDefinition<ObjectBoxAlbumTrashEntry>(
          model: _entities[3],
          toOneRelations: (ObjectBoxAlbumTrashEntry object) => [],
          toManyRelations: (ObjectBoxAlbumTrashEntry object) => {},
          getId: (ObjectBoxAlbumTrashEntry object) => object.id,
          setId: (ObjectBoxAlbumTrashEntry object, int id) {
            object.id = id;
          },
          objectToFB: (ObjectBoxAlbumTrashEntry object, fb.Builder fbb) {
            final albumIdOffset = fbb.writeString(object.albumId);
            fbb.startTable(4);
            fbb.addInt64(0, object.id);
            fbb.addOffset(1, albumIdOffset);
            fbb.addInt64(2, object.trashedAt.millisecondsSinceEpoch);
            fbb.finish(fbb.endTable());
            return object.id;
          },
          objectFromFB: (obx.Store store, ByteData fbData) {
            final buffer = fb.BufferContext(fbData);
            final rootOffset = buffer.derefObject(0);
            final albumIdParam = const fb.StringReader(
              asciiOptimization: true,
            ).vTableGet(buffer, rootOffset, 6, '');
            final trashedAtParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
            );
            final object = ObjectBoxAlbumTrashEntry(
              albumId: albumIdParam,
              trashedAt: trashedAtParam,
            )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

            return object;
          },
        ),
    ObjectBoxImageEmbedding: obx_int.EntityDefinition<ObjectBoxImageEmbedding>(
      model: _entities[4],
      toOneRelations: (ObjectBoxImageEmbedding object) => [],
      toManyRelations: (ObjectBoxImageEmbedding object) => {},
      getId: (ObjectBoxImageEmbedding object) => object.id,
      setId: (ObjectBoxImageEmbedding object, int id) {
        object.id = id;
      },
      objectToFB: (ObjectBoxImageEmbedding object, fb.Builder fbb) {
        final assetIdOffset = fbb.writeString(object.assetId);
        final titleOffset = fbb.writeString(object.title);
        final embeddingOffset = fbb.writeListFloat32(object.embedding);
        fbb.startTable(11);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, assetIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addInt64(3, object.mediaType);
        fbb.addInt64(4, object.duration);
        fbb.addOffset(5, embeddingOffset);
        fbb.addInt64(6, object.indexedAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.mediaCreatedAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.mediaModifiedAt.millisecondsSinceEpoch);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final assetIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final mediaTypeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final durationParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final mediaCreatedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final mediaModifiedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0),
        );
        final object =
            ObjectBoxImageEmbedding(
                assetId: assetIdParam,
                title: titleParam,
                mediaType: mediaTypeParam,
                duration: durationParam,
                embedding: embeddingParam,
                mediaCreatedAt: mediaCreatedAtParam,
                mediaModifiedAt: mediaModifiedAtParam,
              )
              ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
              ..indexedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
              )
              ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
              );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [SearchQuery] entity fields to define ObjectBox queries.
class SearchQuery_ {
  /// See [SearchQuery.id].
  static final id = obx.QueryIntegerProperty<SearchQuery>(
    _entities[0].properties[0],
  );

  /// See [SearchQuery.text].
  static final text = obx.QueryStringProperty<SearchQuery>(
    _entities[0].properties[1],
  );

  /// See [SearchQuery.createdAt].
  static final createdAt = obx.QueryDateProperty<SearchQuery>(
    _entities[0].properties[2],
  );
}

/// [ObjectBoxTrashEntry] entity fields to define ObjectBox queries.
class ObjectBoxTrashEntry_ {
  /// See [ObjectBoxTrashEntry.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxTrashEntry>(
    _entities[1].properties[0],
  );

  /// See [ObjectBoxTrashEntry.assetId].
  static final assetId = obx.QueryStringProperty<ObjectBoxTrashEntry>(
    _entities[1].properties[1],
  );

  /// See [ObjectBoxTrashEntry.trashedAt].
  static final trashedAt = obx.QueryDateProperty<ObjectBoxTrashEntry>(
    _entities[1].properties[2],
  );
}

/// [ObjectBoxAlbum] entity fields to define ObjectBox queries.
class ObjectBoxAlbum_ {
  /// See [ObjectBoxAlbum.objectBoxId].
  static final objectBoxId = obx.QueryIntegerProperty<ObjectBoxAlbum>(
    _entities[2].properties[0],
  );

  /// See [ObjectBoxAlbum.title].
  static final title = obx.QueryStringProperty<ObjectBoxAlbum>(
    _entities[2].properties[1],
  );

  /// See [ObjectBoxAlbum.description].
  static final description = obx.QueryStringProperty<ObjectBoxAlbum>(
    _entities[2].properties[2],
  );

  /// See [ObjectBoxAlbum.platformId].
  static final platformId = obx.QueryStringProperty<ObjectBoxAlbum>(
    _entities[2].properties[3],
  );
}

/// [ObjectBoxAlbumTrashEntry] entity fields to define ObjectBox queries.
class ObjectBoxAlbumTrashEntry_ {
  /// See [ObjectBoxAlbumTrashEntry.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxAlbumTrashEntry>(
    _entities[3].properties[0],
  );

  /// See [ObjectBoxAlbumTrashEntry.albumId].
  static final albumId = obx.QueryStringProperty<ObjectBoxAlbumTrashEntry>(
    _entities[3].properties[1],
  );

  /// See [ObjectBoxAlbumTrashEntry.trashedAt].
  static final trashedAt = obx.QueryDateProperty<ObjectBoxAlbumTrashEntry>(
    _entities[3].properties[2],
  );
}

/// [ObjectBoxImageEmbedding] entity fields to define ObjectBox queries.
class ObjectBoxImageEmbedding_ {
  /// See [ObjectBoxImageEmbedding.id].
  static final id = obx.QueryIntegerProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[0],
  );

  /// See [ObjectBoxImageEmbedding.assetId].
  static final assetId = obx.QueryStringProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[1],
  );

  /// See [ObjectBoxImageEmbedding.title].
  static final title = obx.QueryStringProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[2],
  );

  /// See [ObjectBoxImageEmbedding.mediaType].
  static final mediaType = obx.QueryIntegerProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[3],
  );

  /// See [ObjectBoxImageEmbedding.duration].
  static final duration = obx.QueryIntegerProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[4],
  );

  /// See [ObjectBoxImageEmbedding.embedding].
  static final embedding = obx.QueryHnswProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[5],
  );

  /// See [ObjectBoxImageEmbedding.indexedAt].
  static final indexedAt = obx.QueryDateProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[6],
  );

  /// See [ObjectBoxImageEmbedding.mediaCreatedAt].
  static final mediaCreatedAt = obx.QueryDateProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[7],
  );

  /// See [ObjectBoxImageEmbedding.mediaModifiedAt].
  static final mediaModifiedAt = obx.QueryDateProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[8],
  );

  /// See [ObjectBoxImageEmbedding.createdAt].
  static final createdAt = obx.QueryDateProperty<ObjectBoxImageEmbedding>(
    _entities[4].properties[9],
  );
}
